# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff158aed29bbf290f5acdc9359f790483aa5d69279004f15fabd8cf5551ced95c6483e16ee4d270ef3d7296bc8f7f4050fca202bcb936559ca356a425f81b6d1

test:
  secret_key_base: 11d2375454e0676f3ab63543480c7090c622afc561b92e72926344a7f12b7ef5defd5a510750b522c16196e261a0518540b4bcb16b50ab563ca99437f32b33b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
